# Generated by Django 6.0.5 on 2026-05-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('sector_focal_point', 'Sector Focal Point'), ('public', 'Public')], default='sector_focal_point', max_length=50)),
                ('assigned_sector', models.CharField(blank=True, choices=[('energy', 'Energy'), ('agriculture', 'Agriculture'), ('lulucf', 'Land Use, Land-Use Change and Forestry'), ('waste', 'Waste'), ('ippu', 'Industrial Processes and Product Use'), ('projects', 'Projects'), ('none', 'None')], default='none', max_length=50)),
                ('ministry_department', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('is_active_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.lgaregistry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
