# Generated by Django 6.0.5 on 2026-05-25 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('climate_risk', 'Climate Risk Report'), ('ghg_inventory', 'GHG Inventory Report'), ('project_portfolio', 'Project Portfolio Report'), ('ndc_progress', 'NDC Progress Report'), ('executive_brief', 'Executive Brief'), ('data_export', 'Data Export'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('reporting_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('source_module', models.CharField(blank=True, help_text='Example: climate_risk, ghg_inventory, project_portfolio.', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['report_type'], name='reports_rep_report__a5b1c1_idx'), models.Index(fields=['status'], name='reports_rep_status_a2da61_idx'), models.Index(fields=['reporting_year'], name='reports_rep_reporti_8465ea_idx'), models.Index(fields=['source_module'], name='reports_rep_source__a9a3f0_idx'), models.Index(fields=['is_public'], name='reports_rep_is_publ_b472af_idx'), models.Index(fields=['is_active'], name='reports_rep_is_acti_49b7e9_idx')],
            },
        ),
    ]
