# Generated by Django 6.0.5 on 2026-05-25 10:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(choices=[('adaptation', 'Adaptation'), ('mitigation', 'Mitigation'), ('cross_cutting', 'Cross-cutting')], default='adaptation', max_length=50)),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('agriculture', 'Agriculture'), ('waste', 'Waste'), ('ippu', 'IPPU'), ('lulucf', 'LULUCF'), ('water', 'Water'), ('health', 'Health'), ('infrastructure', 'Infrastructure'), ('disaster_risk', 'Disaster Risk Management'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='proposed', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('implementing_agency', models.CharField(blank=True, max_length=255)),
                ('funding_source', models.CharField(blank=True, max_length=255)),
                ('estimated_budget_naira', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('expected_ghg_reduction_tco2e', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Expected mitigation outcome in tonnes CO2e.', max_digits=18)),
                ('expected_beneficiaries', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('climate_risk_relevance', models.TextField(blank=True, help_text='Explain how this project responds to flood, drought, heat, erosion, vulnerability or adaptive capacity needs.')),
                ('location_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_climate_projects', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_projects', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['project_type'], name='projects_cl_project_2f3ae3_idx'), models.Index(fields=['sector'], name='projects_cl_sector_40a569_idx'), models.Index(fields=['status'], name='projects_cl_status_680948_idx'), models.Index(fields=['priority'], name='projects_cl_priorit_412511_idx'), models.Index(fields=['lga'], name='projects_cl_lga_id_448e1e_idx')],
            },
        ),
    ]
