# Generated by Django 6.0.5 on 2026-06-09 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='climateproject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Project latitude in WGS84 decimal degrees.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='climateproject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Project longitude in WGS84 decimal degrees.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='climateproject',
            name='project_image',
            field=models.ImageField(blank=True, help_text='Public-facing project image for the project showcase.', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='climateproject',
            name='public_description',
            field=models.TextField(blank=True, help_text='Longer public-facing description used for read-more details.'),
        ),
        migrations.AddField(
            model_name='climateproject',
            name='public_summary',
            field=models.CharField(blank=True, help_text='Short public summary shown on project showcase cards.', max_length=300),
        ),
        migrations.AddIndex(
            model_name='climateproject',
            index=models.Index(fields=['latitude', 'longitude'], name='projects_cl_latitud_b6395b_idx'),
        ),
        migrations.AddIndex(
            model_name='climateproject',
            index=models.Index(fields=['funding_source'], name='projects_cl_funding_c7fe6c_idx'),
        ),
    ]
