# Generated by Django 6.0.5 on 2026-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_climateproject_latitude_climateproject_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateproject',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional external project resource link (official page, donor page, report).', max_length=500, null=True),
        ),
    ]
