# Generated by Django 6.0.5 on 2026-07-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('phc', 'Primary Health Centre'), ('secondary', 'Secondary Hospital'), ('tertiary', 'Tertiary Hospital'), ('clinic', 'Clinic'), ('maternity', 'Maternity Home'), ('dispensary', 'Dispensary'), ('other', 'Other')], default='other', max_length=30)),
                ('ownership', models.CharField(choices=[('public', 'Public (Government)'), ('private', 'Private'), ('faith_based', 'Faith-Based'), ('ngo', 'NGO / International')], default='public', max_length=20)),
                ('state', models.CharField(default='Kaduna', max_length=100)),
                ('lga_name', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('functional_status', models.CharField(choices=[('functional', 'Functional'), ('partial', 'Partially Functional'), ('non_functional', 'Non-Functional'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('bed_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('population_served', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='core.lgaregistry')),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
                'ordering': ['lga_name', 'name'],
                'indexes': [models.Index(fields=['lga'], name='infra_hf_lga_idx'), models.Index(fields=['facility_type'], name='infra_hf_type_idx'), models.Index(fields=['functional_status'], name='infra_hf_status_idx'), models.Index(fields=['state', 'lga_name'], name='infra_hf_state_lga_idx'), models.Index(fields=['latitude', 'longitude'], name='infra_hf_latlon_idx')],
            },
        ),
    ]
