function escapeCsvValue(value) {
  const text = String(value ?? "");

  if (text.includes(",") || text.includes('"') || text.includes("\n")) {
    return `"${text.replace(/"/g, '""')}"`;
  }

  return text;
}

function downloadCsv(filename, rows) {
  const csvContent = rows
    .map((row) => row.map((cell) => escapeCsvValue(cell)).join(","))
    .join("\n");

  const blob = new Blob([csvContent], {
    type: "text/csv;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

function getTimestamp() {
  return new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
}

function buildReportRows(reports) {
  return [
    [
      "Report ID",
      "Title",
      "Report Type",
      "Status",
      "Reporting Year",
      "Source Module",
      "Visibility",
      "Generated By",
      "Approved By",
      "Approved At",
      "File URL",
      "Description",
      "Notes",
      "Created At",
      "Updated At",
    ],
    ...reports.map((report) => [
      report.id,
      report.title || "",
      report.report_type_display || report.report_type || "",
      report.status_display || report.status || "",
      report.reporting_year || "",
      report.source_module || "",
      report.is_public ? "Public" : "Internal",
      report.generated_by_name || "",
      report.approved_by_name || "",
      report.approved_at || "",
      report.file_url || "",
      report.description || "",
      report.notes || "",
      report.created_at || "",
      report.updated_at || "",
    ]),
  ];
}

function buildSummaryRows(reports, summary) {
  const byType = summary?.by_type || {};
  const byStatus = summary?.by_status || {};

  return [
    ["Metric", "Value"],
    ["Total Reports", summary?.total_reports || reports.length],
    ["Public Reports", summary?.public_reports || 0],
    ["Approved Reports", summary?.approved_reports || 0],
    ["Published Reports", summary?.published_reports || 0],
    ["Climate Risk Reports", byType.climate_risk || 0],
    ["GHG Inventory Reports", byType.ghg_inventory || 0],
    ["Project Portfolio Reports", byType.project_portfolio || 0],
    ["NDC Progress Reports", byType.ndc_progress || 0],
    ["Executive Briefs", byType.executive_brief || 0],
    ["Data Exports", byType.data_export || 0],
    ["Other Reports", byType.other || 0],
    ["Draft Reports", byStatus.draft || 0],
    ["Under Review Reports", byStatus.review || 0],
    ["Approved Status Reports", byStatus.approved || 0],
    ["Published Status Reports", byStatus.published || 0],
    ["Archived Reports", byStatus.archived || 0],
  ];
}

export default function ReportsCentreExportPanel({
  reports = [],
  filteredReports = [],
  summary = {},
}) {
  function exportFilteredReports() {
    downloadCsv(
      `reports_filtered_${getTimestamp()}.csv`,
      buildReportRows(filteredReports)
    );
  }

  function exportAllLoadedReports() {
    downloadCsv(
      `reports_all_loaded_${getTimestamp()}.csv`,
      buildReportRows(reports)
    );
  }

  function exportReportsSummary() {
    downloadCsv(
      `reports_summary_${getTimestamp()}.csv`,
      buildSummaryRows(reports, summary)
    );
  }

  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start">
        <div>
          <p className="text-sm font-medium text-emerald-700">
            Export Readiness
          </p>
          <h2 className="mt-1 text-lg font-bold">Reports Centre CSV Exports</h2>
          <p className="mt-1 max-w-3xl text-sm text-slate-500">
            Export filtered report records, all loaded reports, or a summary
            table for review, audit tracking, Excel analysis, and briefings.
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
            type="button"
            onClick={exportFilteredReports}
            className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700"
          >
            Export Filtered Reports
          </button>

          <button
            type="button"
            onClick={exportAllLoadedReports}
            className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            Export All Loaded
          </button>

          <button
            type="button"
            onClick={exportReportsSummary}
            className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-100"
          >
            Export Summary
          </button>
        </div>
      </div>

      <div className="mt-5 grid gap-4 md:grid-cols-3">
        <div className="rounded-2xl bg-slate-50 p-4">
          <p className="text-sm text-slate-500">Filtered Reports</p>
          <p className="mt-2 text-2xl font-bold">{filteredReports.length}</p>
        </div>

        <div className="rounded-2xl bg-slate-50 p-4">
          <p className="text-sm text-slate-500">All Loaded Reports</p>
          <p className="mt-2 text-2xl font-bold">{reports.length}</p>
        </div>

        <div className="rounded-2xl bg-slate-50 p-4">
          <p className="text-sm text-slate-500">Public Reports in Filter</p>
          <p className="mt-2 text-2xl font-bold">
            {filteredReports.filter((report) => report.is_public).length}
          </p>
        </div>
      </div>
    </section>
  );
}