function formatNumber(value, maximumFractionDigits = 0) {
  return Number(value || 0).toLocaleString(undefined, {
    maximumFractionDigits,
  });
}

function escapeCsvValue(value) {
  const text = String(value ?? "");

  if (text.includes(",") || text.includes('"') || text.includes("\n")) {
    return `"${text.replace(/"/g, '""')}"`;
  }

  return text;
}

function downloadCsv(filename, rows) {
  const csvContent = rows
    .map((row) => row.map((cell) => escapeCsvValue(cell)).join(","))
    .join("\n");

  const blob = new Blob([csvContent], {
    type: "text/csv;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

function getTimestamp() {
  return new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
}

function buildReportRows(reports) {
  return [
    [
      "Report ID",
      "Title",
      "Report Type",
      "Status",
      "Reporting Year",
      "Source Module",
      "Visibility",
      "Generated By",
      "Approved By",
      "Approved At",
      "File URL",
      "Description",
      "Notes",
      "Created At",
      "Updated At",
    ],
    ...reports.map((report) => [
      report.id,
      report.title || "",
      report.report_type_display || report.report_type || "",
      report.status_display || report.status || "",
      report.reporting_year || "",
      report.source_module || "",
      report.is_public ? "Public" : "Internal",
      report.generated_by_name || "",
      report.approved_by_name || "",
      report.approved_at || "",
      report.file_url || "",
      report.description || "",
      report.notes || "",
      report.created_at || "",
      report.updated_at || "",
    ]),
  ];
}

function buildSummaryRows(reports, summary) {
  const byType = summary?.by_type || {};
  const byStatus = summary?.by_status || {};

  return [
    ["Metric", "Value"],
    ["Total Reports", summary?.total_reports || reports.length],
    ["Public Reports", summary?.public_reports || 0],
    ["Approved Reports", summary?.approved_reports || 0],
    ["Published Reports", summary?.published_reports || 0],
    ["Climate Intelligence Reports", byType.climate_risk || 0],
    ["GHG Inventory Reports", byType.ghg_inventory || 0],
    ["Project Portfolio Reports", byType.project_portfolio || 0],
    ["NDC Progress Reports", byType.ndc_progress || 0],
    ["Executive Briefs", byType.executive_brief || 0],
    ["Data Exports", byType.data_export || 0],
    ["Other Reports", byType.other || 0],
    ["Draft Reports", byStatus.draft || 0],
    ["Under Review Reports", byStatus.review || 0],
    ["Approved Status Reports", byStatus.approved || 0],
    ["Published Status Reports", byStatus.published || 0],
    ["Archived Reports", byStatus.archived || 0],
  ];
}

function ExportMetric({ label, value, helper, tone = "blue" }) {
  const toneClasses = {
    blue: "border-[#030454]/15 bg-[#030454]/5",
    green: "border-[#009B35]/20 bg-[#009B35]/8",
    yellow: "border-[#F3F74B]/70 bg-[#F3F74B]/25",
  };

  return (
    <div
      className={`rounded-xl border p-4 shadow-sm ${
        toneClasses[tone] || toneClasses.blue
      }`}
    >
      <p className="text-xs font-black uppercase tracking-[0.14em] text-slate-500">
        {label}
      </p>

      <p className="mt-2 text-2xl font-black text-[#030454]">{value}</p>

      {helper && <p className="mt-1 text-xs text-slate-500">{helper}</p>}
    </div>
  );
}

export default function ReportsCentreExportPanel({
  reports = [],
  filteredReports = [],
  summary = {},
}) {
  function exportFilteredReports() {
    downloadCsv(
      `reports_filtered_${getTimestamp()}.csv`,
      buildReportRows(filteredReports)
    );
  }

  function exportAllLoadedReports() {
    downloadCsv(
      `reports_all_loaded_${getTimestamp()}.csv`,
      buildReportRows(reports)
    );
  }

  function exportReportsSummary() {
    downloadCsv(
      `reports_summary_${getTimestamp()}.csv`,
      buildSummaryRows(reports, summary)
    );
  }

  const publicReportsInFilter = filteredReports.filter(
    (report) => report.is_public
  ).length;

  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start">
        <div>
          <p className="text-xs font-black uppercase tracking-[0.14em] text-[#009B35]">
            Export Readiness
          </p>

          <h2 className="mt-2 text-2xl font-black text-[#030454]">
            Reports Centre CSV Exports
          </h2>

          <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
            Export filtered report records, all loaded reports, or a summary
            table for review, audit tracking, Excel analysis and briefings.
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
            type="button"
            onClick={exportFilteredReports}
            className="rounded-md bg-[#009B35] px-5 py-3 text-xs font-black uppercase tracking-[0.08em] text-white transition hover:bg-[#00842e]"
          >
            Export Filtered
          </button>

          <button
            type="button"
            onClick={exportAllLoadedReports}
            className="rounded-md border border-slate-200 bg-white px-5 py-3 text-xs font-black uppercase tracking-[0.08em] text-[#030454] transition hover:border-[#009B35] hover:text-[#009B35]"
          >
            Export All Loaded
          </button>

          <button
            type="button"
            onClick={exportReportsSummary}
            className="rounded-md bg-[#030454] px-5 py-3 text-xs font-black uppercase tracking-[0.08em] text-white transition hover:bg-[#02033d]"
          >
            Export Summary
          </button>
        </div>
      </div>

      <div className="mt-6 grid gap-4 md:grid-cols-3">
        <ExportMetric
          label="Filtered Reports"
          value={formatNumber(filteredReports.length)}
          helper="Records matching current filters."
          tone="green"
        />

        <ExportMetric
          label="All Loaded Reports"
          value={formatNumber(reports.length)}
          helper="Records loaded from the API."
          tone="blue"
        />

        <ExportMetric
          label="Public Reports in Filter"
          value={formatNumber(publicReportsInFilter)}
          helper="Filtered records marked public."
          tone="yellow"
        />
      </div>
    </section>
  );
}