# Generated by Django 6.0.5 on 2026-05-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('agriculture', 'Agriculture'), ('lulucf', 'LULUCF'), ('waste', 'Waste'), ('ippu', 'IPPU')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('total_co2e', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(default='computed', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'sector'],
                'unique_together': {('sector', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GHGInventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('agriculture', 'Agriculture'), ('lulucf', 'LULUCF'), ('waste', 'Waste'), ('ippu', 'IPPU')], default='energy', max_length=50)),
                ('sub_category', models.CharField(max_length=100)),
                ('fuel_or_activity', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit', models.CharField(default='metric_tonnes', max_length=50)),
                ('co2_kg', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('ch4_kg', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('n2o_kg', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('co2e_tonnes', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ghg_entries', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ghg_entries', to='core.emissionfactor')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghg_entries', to='core.lgaregistry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ghg_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'fuel_or_activity'],
                'indexes': [models.Index(fields=['sector', 'year', 'status'], name='ghg_ghginve_sector_0244a8_idx'), models.Index(fields=['sector', 'sub_category', 'fuel_or_activity', 'year'], name='ghg_ghginve_sector_80ef44_idx')],
            },
        ),
    ]
