# Generated by Django 6.0.5 on 2026-05-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('flood_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('drought_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heat_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('erosion_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vulnerability_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adaptive_capacity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='moderate', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.CharField(default='Development seed data', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_risk_profiles', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['-overall_risk_score', 'lga__lga_name'],
                'indexes': [models.Index(fields=['year', 'risk_level'], name='climate_ris_year_2b666e_idx'), models.Index(fields=['overall_risk_score'], name='climate_ris_overall_5378cb_idx')],
                'unique_together': {('lga', 'year')},
            },
        ),
    ]
