# Generated by Django 6.0.5 on 2026-05-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_risk', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRiskParameterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('category', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('heat', 'Heat'), ('erosion', 'Erosion'), ('vulnerability', 'Vulnerability'), ('adaptive_capacity', 'Adaptive Capacity')], max_length=50)),
                ('parameter_key', models.SlugField(max_length=100)),
                ('parameter_label', models.CharField(max_length=150)),
                ('raw_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional 0-100 normalized score. Later this will be calculated automatically.', max_digits=5, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_risk_parameter_records', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['lga__lga_name', 'category', 'parameter_label'],
                'indexes': [models.Index(fields=['year', 'category'], name='climate_ris_year_b2ef81_idx'), models.Index(fields=['lga', 'year'], name='climate_ris_lga_id_141f3f_idx')],
                'unique_together': {('lga', 'year', 'category', 'parameter_key')},
            },
        ),
    ]
