# Generated by Django 6.0.5 on 2026-05-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_risk', '0002_climateriskparameterrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='climateriskprofile',
            name='dominant_hazard',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='climateriskprofile',
            name='exposure_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='climateriskparameterrecord',
            name='category',
            field=models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('heat', 'Heat'), ('erosion', 'Erosion'), ('exposure', 'Exposure'), ('vulnerability', 'Vulnerability'), ('adaptive_capacity', 'Adaptive Capacity')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClimateRiskDatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('flood_scores', 'Flood Scores CSV'), ('drought_scores', 'Drought Scores CSV'), ('heat_scores', 'Heat Scores CSV'), ('erosion_scores', 'Erosion Scores CSV'), ('exposure_scores', 'Exposure Scores CSV'), ('vulnerability_scores', 'Vulnerability Scores CSV'), ('adaptive_capacity_scores', 'Adaptive Capacity Scores CSV'), ('parameter_records', 'Generic Parameter Records CSV')], max_length=80)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='processing', max_length=50)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_risk_dataset_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset_type', 'year'], name='climate_ris_dataset_912d84_idx'), models.Index(fields=['status'], name='climate_ris_status_c8ec45_idx')],
            },
        ),
    ]
