# Generated by Django 6.0.5 on 2026-05-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_risk', '0003_climateriskprofile_dominant_hazard_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateInfrastructureAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('asset_type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('market', 'Market'), ('road_bridge', 'Road / Bridge'), ('water_facility', 'Water Facility'), ('settlement', 'Settlement'), ('government_facility', 'Government Facility'), ('other', 'Other')], default='other', max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('exposure_score', models.DecimalField(decimal_places=2, default=0, help_text='Normalized exposure score from 0 to 100.', max_digits=5)),
                ('risk_status', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='moderate', max_length=50)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_infrastructure_assets', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['lga__lga_name', 'asset_type', 'asset_name'],
                'indexes': [models.Index(fields=['lga', 'year'], name='climate_ris_lga_id_6ed38c_idx'), models.Index(fields=['asset_type'], name='climate_ris_asset_t_a60f83_idx'), models.Index(fields=['risk_status'], name='climate_ris_risk_st_33b3c4_idx')],
            },
        ),
    ]
