import { useEffect, useMemo, useState } from "react";
import {
  PublicEmptyState,
  PublicPortalFooter,
  PublicPortalHeader,
  PublicSectionIntro,
} from "../components/PublicPortalChrome";
import { getPublicReportDocuments } from "../services/api";

const reportTypeOptions = [
  { value: "climate_risk", label: "Climate Risk Report" },
  { value: "ghg_inventory", label: "GHG Inventory Report" },
  { value: "project_portfolio", label: "Project Portfolio Report" },
  { value: "ndc_progress", label: "NDC Progress Report" },
  { value: "executive_brief", label: "Executive Brief" },
  { value: "data_export", label: "Data Export" },
  { value: "other", label: "Other" },
];

function formatNumber(value, maximumFractionDigits = 0) {
  return Number(value || 0).toLocaleString(undefined, {
    maximumFractionDigits,
  });
}

function getOptionLabel(options, value) {
  return options.find((item) => item.value === value)?.label || value || "—";
}

function getReportFileUrl(report) {
  return (
    report.file_url ||
    report.document_url ||
    report.file ||
    report.download_url ||
    ""
  );
}

function normalizeReportsPayload(data) {
  if (Array.isArray(data)) {
    return {
      results: data,
      summary: {},
    };
  }

  return {
    results: data?.results || data?.reports || [],
    summary: data?.summary || {},
  };
}

function getTypeClass(type) {
  if (type === "climate_risk") return "bg-[#009B35]/10 text-[#009B35]";
  if (type === "ghg_inventory") return "bg-[#030454]/10 text-[#030454]";
  if (type === "project_portfolio") return "bg-[#F3F74B]/50 text-[#030454]";
  if (type === "ndc_progress") return "bg-orange-50 text-orange-700";
  if (type === "executive_brief") return "bg-indigo-50 text-indigo-700";
  if (type === "data_export") return "bg-cyan-50 text-cyan-700";
  return "bg-slate-100 text-slate-700";
}

function StatCard({ label, value, helper }) {
  return (
    <div className="rounded-sm border border-slate-200 bg-white p-5 shadow-sm">
      <p className="text-[11px] font-black uppercase tracking-[0.14em] text-slate-500">
        {label}
      </p>

      <p className="mt-3 font-['Playfair_Display'] text-4xl font-bold text-[#030454]">
        {value}
      </p>

      {helper && <p className="mt-2 text-xs leading-5 text-slate-500">{helper}</p>}
    </div>
  );
}

function ReportCard({ report }) {
  const fileUrl = getReportFileUrl(report);

  return (
    <article className="flex h-full flex-col rounded-sm border border-slate-200 bg-white p-6 shadow-sm transition hover:border-[#009B35]/60 hover:shadow-md">
      <div className="mb-4 flex flex-wrap gap-2">
        <span
          className={`rounded-sm px-3 py-1 text-[10px] font-black uppercase tracking-[0.1em] ${getTypeClass(
            report.report_type
          )}`}
        >
          {report.report_type_display ||
            getOptionLabel(reportTypeOptions, report.report_type)}
        </span>

        {report.reporting_year && (
          <span className="rounded-sm bg-slate-100 px-3 py-1 text-[10px] font-black uppercase tracking-[0.1em] text-slate-600">
            {report.reporting_year}
          </span>
        )}
      </div>

      <h3 className="text-xl font-black leading-snug text-[#030454]">
        {report.title}
      </h3>

      <p className="mt-3 line-clamp-3 text-sm leading-7 text-slate-600">
        {report.description || "No report description has been provided."}
      </p>

      <div className="mt-6 grid gap-3 border-t border-slate-200 pt-5 text-xs text-slate-500">
        {report.source_module && (
          <p>
            <span className="font-bold text-[#030454]">Source module:</span>{" "}
            {report.source_module}
          </p>
        )}

        {report.generated_by_name && (
          <p>
            <span className="font-bold text-[#030454]">Generated by:</span>{" "}
            {report.generated_by_name}
          </p>
        )}

        {report.created_at && (
          <p>
            <span className="font-bold text-[#030454]">Uploaded:</span>{" "}
            {new Date(report.created_at).toLocaleDateString()}
          </p>
        )}
      </div>

      <div className="mt-auto pt-6">
        {fileUrl ? (
          <a
            href={fileUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex w-full items-center justify-center rounded-sm bg-[#009B35] px-5 py-3 text-sm font-black uppercase tracking-[0.08em] text-white transition hover:bg-[#00842e]"
          >
            Open Report
          </a>
        ) : (
          <button
            type="button"
            disabled
            className="inline-flex w-full cursor-not-allowed items-center justify-center rounded-sm bg-slate-100 px-5 py-3 text-sm font-black uppercase tracking-[0.08em] text-slate-400"
          >
            File Unavailable
          </button>
        )}
      </div>
    </article>
  );
}

export default function PublicReportsPage() {
  const [reportsData, setReportsData] = useState(null);
  const [filters, setFilters] = useState({
    report_type: "all",
    reporting_year: "",
    search: "",
  });

  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");

  async function loadReports() {
    setIsLoading(true);
    setError("");

    try {
      const params = {};

      if (filters.report_type && filters.report_type !== "all") {
        params.report_type = filters.report_type;
      }

      if (filters.reporting_year) {
        params.reporting_year = filters.reporting_year;
      }

      const data = await getPublicReportDocuments(params);
      setReportsData(normalizeReportsPayload(data));
    } catch (err) {
      console.error(err);
      setError("Could not load public reports.");
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    loadReports();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters.report_type, filters.reporting_year]);

  const reports = reportsData?.results || [];
  const summary = reportsData?.summary || {};

  const filteredReports = useMemo(() => {
    const search = filters.search.trim().toLowerCase();

    if (!search) return reports;

    return reports.filter((report) => {
      return (
        String(report.title || "").toLowerCase().includes(search) ||
        String(report.description || "").toLowerCase().includes(search) ||
        String(report.report_type_display || "")
          .toLowerCase()
          .includes(search) ||
        String(report.source_module || "").toLowerCase().includes(search)
      );
    });
  }, [reports, filters.search]);

  const years = useMemo(() => {
    const yearSet = new Set();

    reports.forEach((report) => {
      if (report.reporting_year) {
        yearSet.add(String(report.reporting_year));
      }
    });

    return Array.from(yearSet).sort((a, b) => Number(b) - Number(a));
  }, [reports]);

  const heroStats = useMemo(() => {
    return [
      {
        label: "Public Reports",
        value: summary.total_reports || reports.length || 0,
      },
      {
        label: "Published Documents",
        value: summary.published_reports || reports.length || 0,
      },
      {
        label: "Report Types",
        value:
          summary.report_type_count ||
          new Set(reports.map((report) => report.report_type).filter(Boolean))
            .size ||
          0,
      },
      {
        label: "Latest Year",
        value:
          summary.latest_year ||
          years[0] ||
          new Date().getFullYear().toString(),
      },
    ];
  }, [summary, reports, years]);

  function updateFilter(field, value) {
    setFilters((current) => ({
      ...current,
      [field]: value,
    }));
  }

  return (
    <main className="min-h-screen bg-white font-['DM_Sans'] text-[#030454]">
      <PublicPortalHeader
        activePage="reports"
        compact
        title={<>Public reports and evidence documents</>}
        description={[
          "Access approved climate reports, evidence documents, public briefs and validated outputs published through the Kaduna Climate Command Centre.",
          "Only documents approved for public access are displayed here.",
        ]}
        stats={heroStats}
        showStats
        showActions={false}
      />

      {error && (
        <section className="px-4 py-4 sm:px-8 lg:px-10">
          <div className="mx-auto max-w-7xl rounded-sm border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            {error}
          </div>
        </section>
      )}

      <section className="px-4 py-16 sm:px-8 lg:px-10 lg:py-20">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-end">
            <PublicSectionIntro
              title="Published reports"
              description="Browse public-facing climate risk reports, greenhouse gas inventory outputs, project portfolio reports, executive briefs and data exports."
            />

            <div className="grid gap-3 md:grid-cols-3">
              <select
                value={filters.report_type}
                onChange={(event) =>
                  updateFilter("report_type", event.target.value)
                }
                className="rounded-sm border border-slate-200 bg-white px-4 py-3 text-sm text-[#030454] outline-none transition focus:border-[#009B35] focus:ring-2 focus:ring-[#009B35]/10"
              >
                <option value="all">All report types</option>
                {reportTypeOptions.map((item) => (
                  <option key={item.value} value={item.value}>
                    {item.label}
                  </option>
                ))}
              </select>

              <select
                value={filters.reporting_year}
                onChange={(event) =>
                  updateFilter("reporting_year", event.target.value)
                }
                className="rounded-sm border border-slate-200 bg-white px-4 py-3 text-sm text-[#030454] outline-none transition focus:border-[#009B35] focus:ring-2 focus:ring-[#009B35]/10"
              >
                <option value="">All years</option>
                {years.map((year) => (
                  <option key={year} value={year}>
                    {year}
                  </option>
                ))}
              </select>

              <input
                value={filters.search}
                onChange={(event) => updateFilter("search", event.target.value)}
                placeholder="Search reports..."
                className="rounded-sm border border-slate-200 bg-white px-4 py-3 text-sm text-[#030454] outline-none transition placeholder:text-slate-400 focus:border-[#009B35] focus:ring-2 focus:ring-[#009B35]/10"
              />
            </div>
          </div>

          <div className="mt-10 grid gap-4 md:grid-cols-3">
            <StatCard
              label="Loaded Reports"
              value={formatNumber(filteredReports.length)}
              helper="Reports currently matching your filters."
            />

            <StatCard
              label="Available Years"
              value={formatNumber(years.length)}
              helper="Reporting years represented in the public library."
            />

            <StatCard
              label="Document Access"
              value="Public"
              helper="Only published and public-facing records are shown."
            />
          </div>

          {isLoading ? (
            <div className="mt-10 rounded-sm border border-slate-200 bg-white p-8 text-sm text-slate-500 shadow-sm">
              Loading public reports...
            </div>
          ) : (
            <div className="mt-10">
              {filteredReports.length > 0 ? (
                <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
                  {filteredReports.map((report) => (
                    <ReportCard key={report.id || report.title} report={report} />
                  ))}
                </div>
              ) : (
                <PublicEmptyState
                  title="No public reports found"
                  message="No published public reports match the selected filters."
                />
              )}
            </div>
          )}
        </div>
      </section>

      <section className="border-y border-slate-200 bg-[#030454] px-4 py-12 text-white sm:px-8 lg:px-10">
        <div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1fr_auto] md:items-center">
          <div>
            <h3 className="font-['Playfair_Display'] text-3xl font-bold">
              Return to climate intelligence portal
            </h3>

            <p className="mt-3 max-w-2xl text-sm font-light leading-7 text-white/70">
              Go back to the public portal to view the climate risk map, public
              project summary and partner information.
            </p>
          </div>

          <button
            type="button"
            onClick={() => {
              window.location.href = "/public";
            }}
            className="w-fit rounded-sm bg-[#009B35] px-6 py-3 text-sm font-black uppercase tracking-[0.08em] text-white transition hover:bg-[#00842e]"
          >
            Back to Public Portal
          </button>
        </div>
      </section>

      <PublicPortalFooter />
    </main>
  );
}