# Generated by Django 6.0.5 on 2026-06-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSensingLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ndvi', 'NDVI / Vegetation Condition'), ('lst', 'Land Surface Temperature'), ('temperature_anomaly', 'Temperature Anomaly'), ('rainfall', 'Rainfall'), ('rainfall_anomaly', 'Rainfall Anomaly'), ('flood_hazard', 'Flood Hazard'), ('flood_occurrence', 'Flood Occurrence'), ('drought_index', 'Drought Index'), ('lulc', 'Land Use / Land Cover'), ('elevation', 'Elevation / Terrain'), ('tree_cover', 'Tree Cover'), ('forest_change', 'Forest Change')], max_length=80, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('gee_dataset', models.CharField(blank=True, max_length=255)),
                ('gee_band', models.CharField(blank=True, max_length=120)),
                ('visualization', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RemoteSensingSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='remote_sensing.remotesensinglayer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteSensingLGAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mean_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('anomaly_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_metrics', to='remote_sensing.remotesensinglayer')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sensing_metrics', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['lga__lga_name', '-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='remote_sens_year_7c05e1_idx'), models.Index(fields=['layer', 'year'], name='remote_sens_layer_i_063cf1_idx'), models.Index(fields=['lga', 'year'], name='remote_sens_lga_id_c40b2a_idx')],
                'unique_together': {('layer', 'lga', 'year', 'month')},
            },
        ),
    ]
