# Generated by Django 6.0.5 on 2026-06-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('remote_sensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotesensinglgametric',
            options={'ordering': ['admin_name', '-year']},
        ),
        migrations.RemoveIndex(
            model_name='remotesensinglgametric',
            name='remote_sens_year_7c05e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='remotesensinglgametric',
            name='remote_sens_layer_i_063cf1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='remotesensinglgametric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remotesensinglgametric',
            name='admin_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remotesensinglgametric',
            name='admin_level',
            field=models.CharField(choices=[('lga', 'LGA'), ('ward', 'Ward')], default='lga', max_length=10),
        ),
        migrations.AddField(
            model_name='remotesensinglgametric',
            name='admin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='remotesensinglgametric',
            name='season',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('wet_season', 'Wet Season'), ('dry_season', 'Dry Season')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='remotesensinglgametric',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_sensing_metrics', to='core.lgaregistry'),
        ),
        migrations.AddIndex(
            model_name='remotesensinglgametric',
            index=models.Index(fields=['admin_level', 'admin_code'], name='remote_sens_admin_l_de144f_idx'),
        ),
        migrations.AddIndex(
            model_name='remotesensinglgametric',
            index=models.Index(fields=['layer', 'year', 'season'], name='remote_sens_layer_i_c3f5c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='remotesensinglgametric',
            constraint=models.UniqueConstraint(condition=models.Q(('lga__isnull', False)), fields=('layer', 'lga', 'year', 'month'), name='uniq_rs_lga_month'),
        ),
        migrations.AddConstraint(
            model_name='remotesensinglgametric',
            constraint=models.UniqueConstraint(fields=('layer', 'admin_level', 'admin_code', 'year', 'season'), name='uniq_rs_admin_season'),
        ),
    ]
