# Generated by Django 6.0.5 on 2026-06-29 22:03

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('remote_sensing', '0002_ndvi_admin_season_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotesensinglayer',
            name='key',
            field=models.CharField(choices=[('ndvi', 'NDVI / Vegetation Condition'), ('ndvi_landsat', 'Historical NDVI (Landsat Collection 2)'), ('lst', 'Land Surface Temperature'), ('temperature_anomaly', 'Temperature Anomaly'), ('rainfall', 'Rainfall'), ('rainfall_anomaly', 'Rainfall Anomaly'), ('flood_hazard', 'Flood Hazard'), ('flood_occurrence', 'Flood Occurrence'), ('drought_index', 'Drought Index'), ('lulc', 'Land Use / Land Cover'), ('elevation', 'Elevation / Terrain'), ('tree_cover', 'Tree Cover'), ('forest_change', 'Forest Change')], max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='LandCoverDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80)),
                ('provider_label', models.CharField(max_length=200)),
                ('gee_collection', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('composite_window', models.CharField(choices=[('wet_season', 'Wet Season (May–October)'), ('annual', 'Annual (Jan–Dec)')], default='wet_season', max_length=20)),
                ('composite_start', models.DateField()),
                ('composite_end', models.DateField()),
                ('method_version', models.CharField(max_length=100)),
                ('admin_level', models.CharField(choices=[('lga', 'LGA'), ('ward', 'Ward')], default='lga', max_length=10)),
                ('snapshot_count', models.PositiveSmallIntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_cover_datasets', to='remote_sensing.remotesensingsynclog')),
            ],
            options={
                'ordering': ['-year', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='LandCoverSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('lga', 'LGA'), ('ward', 'Ward')], default='lga', max_length=10)),
                ('admin_code', models.CharField(db_index=True, max_length=50)),
                ('admin_name', models.CharField(max_length=150)),
                ('total_area_km2', models.DecimalField(decimal_places=4, max_digits=12)),
                ('class_pct', models.JSONField()),
                ('class_areas_km2', models.JSONField()),
                ('pixel_count', models.PositiveIntegerField(blank=True, null=True)),
                ('masked_pixel_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='remote_sensing.landcoverdataset')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_cover_snapshots', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['admin_name'],
            },
        ),
        migrations.CreateModel(
            name='LandCoverDerivedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_version', models.CharField(default='lc_change_arithmetic_v1', max_length=100)),
                ('class_change_pct', models.JSONField()),
                ('largest_gain_class', models.CharField(blank=True, max_length=50)),
                ('largest_gain_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('largest_loss_class', models.CharField(blank=True, max_length=50)),
                ('largest_loss_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('baseline_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_as_baseline', to='remote_sensing.landcoversnapshot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_metrics', to='remote_sensing.landcoversnapshot')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='landcoverdataset',
            index=models.Index(fields=['provider', 'year', 'is_public'], name='remote_sens_provide_811c5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='landcoverdataset',
            constraint=models.UniqueConstraint(fields=('provider', 'year', 'composite_window', 'admin_level'), name='uniq_lc_dataset'),
        ),
        migrations.AddIndex(
            model_name='landcoversnapshot',
            index=models.Index(fields=['admin_level', 'admin_code'], name='remote_sens_admin_l_fb2048_idx'),
        ),
        migrations.AddIndex(
            model_name='landcoversnapshot',
            index=models.Index(fields=['dataset'], name='remote_sens_dataset_702f89_idx'),
        ),
        migrations.AddIndex(
            model_name='landcoversnapshot',
            index=django.contrib.postgres.indexes.GinIndex(fields=['class_pct'], name='lc_snapshot_class_pct_gin'),
        ),
        migrations.AddConstraint(
            model_name='landcoversnapshot',
            constraint=models.UniqueConstraint(fields=('dataset', 'admin_level', 'admin_code'), name='uniq_lc_snapshot'),
        ),
        migrations.AddIndex(
            model_name='landcoverderivedmetric',
            index=models.Index(fields=['snapshot'], name='remote_sens_snapsho_200ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='landcoverderivedmetric',
            index=models.Index(fields=['baseline_snapshot'], name='remote_sens_baselin_831d68_idx'),
        ),
        migrations.AddConstraint(
            model_name='landcoverderivedmetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'baseline_snapshot'), name='uniq_lc_derived'),
        ),
    ]
