# Generated by Django 6.0.5 on 2026-05-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalencyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('divisor', models.DecimalField(decimal_places=6, max_digits=16)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GWPValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=20, unique=True)),
                ('gwp100_ar5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(default='IPCC AR5', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LGARegistry',
            fields=[
                ('lga_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('lga_name', models.CharField(max_length=100, unique=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('state', models.CharField(default='Kaduna', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LGA Registry',
                'verbose_name_plural': 'LGA Registry',
                'ordering': ['lga_id'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=150)),
                ('fuel_or_species', models.CharField(max_length=150)),
                ('co2_ef', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('ch4_ef', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('n2o_ef', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('ipcc_source', models.CharField(blank=True, max_length=255)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2')], default='tier_1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('sector', 'sub_category', 'fuel_or_species', 'unit', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('flood_warning', 'Flood Warning'), ('data_overdue', 'Data Overdue'), ('project_off_track', 'Project Off Track'), ('system', 'System')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.lgaregistry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NDCConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nigeria_baseline_mt', models.DecimalField(decimal_places=3, default=317, max_digits=12)),
                ('kaduna_share_pct', models.DecimalField(decimal_places=3, default=4.2, max_digits=6)),
                ('kaduna_baseline_mt', models.DecimalField(decimal_places=3, default=13.3, max_digits=12)),
                ('target_year', models.PositiveIntegerField(default=2030)),
                ('unconditional_pct', models.DecimalField(decimal_places=2, default=47, max_digits=6)),
                ('conditional_pct', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('flood_warning', 'Flood Warning'), ('data_overdue', 'Data Overdue'), ('project_off_track', 'Project Off Track'), ('system', 'System')], max_length=50)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='core.lgaregistry')),
            ],
            options={
                'unique_together': {('user', 'alert_type', 'lga', 'delivery_method')},
            },
        ),
    ]
